export const defaultDateTimeFormat = 'YYYY-MM-DD HH:mm'
export const ISO8601DateTimeFormat = 'YYYY-MM-DDTHH:mm:ssZ'
export const _24HourTimeFormat = 'HH:mm'
export const _12HourTimeFormat = 'hh:mm A'
export const ISODateFormat = 'YYYY-MM-DD'
export const shortDateFormat = 'DD MMM YYYY'
